### ISSUE TITLE
Siperlik V2 STL'si hatalı 

### ISSUE THREAD

**Issue by TeknoBeek** [3-Boyutlu-Destek/siperlik#1]
Repetier water tight olmadığını söylüyor. 
Düzeltilmiş halini yolluyorum. 

[siperlik_v2_fixedd.zip](https://github.com/3-Boyutlu-Destek/siperlik/files/4377808/siperlik_v2_fixedd.zip)

**Comment by orkunasa** [comment]
Merhaba, dün dosyayı güncelleyip v3 yükledik.
